---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/timmas40/public_html
    - /usr/bin/find "$DEPLOYPATH" -mindepth 1 -maxdepth 1 ! -name '.well-known' -exec /bin/rm -rf -- {} +
    - /bin/cp -R out/. "$DEPLOYPATH"/
