export const cities = [
  { name: "Brasília — Plano Piloto", slug: "brasilia-plano-piloto" },
  { name: "Taguatinga", slug: "taguatinga" },
  { name: "Ceilândia", slug: "ceilandia" },
  { name: "Samambaia", slug: "samambaia" },
  { name: "Águas Claras", slug: "aguas-claras" },
  { name: "Guará", slug: "guara" },
  { name: "Gama", slug: "gama" },
  { name: "Santa Maria", slug: "santa-maria" },
  { name: "Recanto das Emas", slug: "recanto-das-emas" },
  { name: "Sobradinho", slug: "sobradinho" },
  { name: "Sobradinho II", slug: "sobradinho-ii" },
  { name: "Planaltina", slug: "planaltina" },
  { name: "Riacho Fundo", slug: "riacho-fundo" },
  { name: "Riacho Fundo II", slug: "riacho-fundo-ii" },
  { name: "Núcleo Bandeirante", slug: "nucleo-bandeirante" },
  { name: "Vicente Pires", slug: "vicente-pires" },
  { name: "São Sebastião", slug: "sao-sebastiao" },
  { name: "Paranoá", slug: "paranoa" },
  { name: "Itapoã", slug: "itapoa" },
  { name: "Brazlândia", slug: "brazlandia" },
];